# Generated by Django 6.0.3 on 2026-04-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('period', models.CharField(default='월', max_length=10)),
                ('value', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('code', 'date')},
            },
        ),
    ]
