# Generated by Django 6.0.3 on 2026-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
