# Generated by Django 6.0.3 on 2026-04-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_indicator_date_indicator_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('code', 'date')},
        ),
    ]
